/// Barrel for the Network subsystem.
///
/// Exported as a whole from `core/di/providers.dart` — add new Network
/// provider/type files here, in the same folder you're already editing,
/// rather than remembering to also touch the distant top-level barrel.
/// See `core/di/providers.dart`'s doc comment for the drift problem this
/// folder-local barrel exists to avoid.
///
/// `connectivity_guard.dart` and `interceptors/retry_interceptor.dart`
/// are deliberately NOT exported here — both are narrow internal wiring
/// types imported directly by the handful of call sites that actually
/// need them (`post_repository_impl.dart` and `dio_client.dart`
/// respectively), not meant to be part of this barrel's general surface.
library;

// dioProvider is generated by riverpod_generator.
export 'connectivity_provider.dart';
export 'dio_client.dart';
// accessTokenReaderProvider is generated by riverpod_generator.
export 'interceptors/auth_interceptor.dart';
// R-08 (27 Jun 2026): derived boolean — watch this instead of
// connectivityStreamProvider in widgets that only need "am I offline?"
export 'offline_provider.dart';
