/// Barrel for the Routing subsystem.
///
/// Exported as a whole from `core/di/providers.dart` — add new Routing
/// provider/type files here, in the same folder you're already editing,
/// rather than remembering to also touch the distant top-level barrel.
/// See `core/di/providers.dart`'s doc comment for the drift problem this
/// folder-local barrel exists to avoid.
///
/// `routes.dart`, `feature_registry.dart`, and `shell_feature.dart` are
/// deliberately NOT exported here — features already import `routes.dart`
/// directly for `AppPath`/`AppRoute` (see e.g. `home_routes.dart`), and
/// `feature_registry.dart`/`shell_feature.dart` are routing-internal
/// wiring that only `app_router.dart` and `nav_destinations.dart` need.
library;

// appRouterProvider is generated by riverpod_generator.
export 'app_router.dart';
