// dart run build_runner build --delete-conflicting-outputs
import 'package:dio/dio.dart';
import 'package:retrofit/retrofit.dart';

import 'package:tokenshell_riverpod/features/posts/data/models/post_model.dart';
import 'package:tokenshell_riverpod/features/posts/presentation/notifiers/posts_notifier.dart';

part 'post_remote_source.g.dart';

/// Retrofit API interface for the /posts resource.
///
/// The concrete implementation ([_PostRemoteSource]) is generated by
// ignore: comment_references
/// [retrofit_generator] into `post_remote_source.g.dart`.
/// Never instantiate this interface directly — use [PostRemoteSourceProvider]
// ignore: comment_references
/// in [providers.dart] to obtain a DI-managed instance.
@RestApi()
abstract interface class PostRemoteSource {
  factory PostRemoteSource(Dio dio, {String baseUrl}) = _PostRemoteSource;

  /// Fetches all posts from GET /posts.
  @GET('/posts')
  Future<List<PostModel>> getPosts();

  /// Fetches a single post from GET /posts/{id}.
  @GET('/posts/{id}')
  Future<PostModel> getPostById(@Path('id') int id);
}
