/// Barrel for the Error-handling subsystem.
///
/// Exported as a whole from `core/di/providers.dart` — add new Error
/// provider/type files here, in the same folder you're already editing,
/// rather than remembering to also touch the distant top-level barrel.
/// See `core/di/providers.dart`'s doc comment for the drift problem this
/// folder-local barrel exists to avoid.
library;

// Pure Dart — no codegen involved; show clause is safe here.
export 'failure.dart' show Failure;
// failureMapperProvider is generated by riverpod_generator — no show
// clause, same rationale as the Network/Theme sections in this barrel's
// sibling subsystem files.
export 'failure_mapper.dart';
