// dart run build_runner build --delete-conflicting-outputs
import 'package:dio/dio.dart';
import 'package:retrofit/retrofit.dart';

import 'package:tokenshell_riverpod/features/posts/data/models/post_model.dart';

part 'post_remote_source.g.dart';

/// Retrofit API interface for the /posts resource.
///
/// The concrete implementation ([_PostRemoteSource]) is generated by
// ignore: comment_references
/// [retrofit_generator] into `post_remote_source.g.dart`.
/// Never instantiate this interface directly — use [PostRemoteSourceProvider]
// ignore: comment_references
/// in [providers.dart] to obtain a DI-managed instance.
@RestApi()
abstract interface class PostRemoteSource {
  factory PostRemoteSource(Dio dio, {String baseUrl}) = _PostRemoteSource;

  /// Fetches posts from GET /posts.
  ///
  /// jsonplaceholder runs on json-server underneath, which supports
  /// `_page` / `_limit` query params for pagination. Both are optional —
  /// when `null`, Dio omits a query parameter from the request entirely
  /// rather than sending it as the literal string `"null"`, so calling
  /// this with no arguments fetches the full unpaginated list exactly as
  /// before.
  @GET('/posts')
  Future<List<PostModel>> getPosts({
    @Query('_page') int? page,
    @Query('_limit') int? pageSize,
  });

  /// Fetches a single post from GET /posts/{id}.
  @GET('/posts/{id}')
  Future<PostModel> getPostById(@Path('id') int id);
}
