/// Central dependency injection barrel.
///
/// Import this single file anywhere in the app to access all infrastructure
/// providers. Feature-level providers (notifiers, use cases) are co-located
/// with their features and do NOT need to be re-exported here.
///
/// Usage:
/// ```dart
/// import 'package:tokenshell_riverpod/core/di/providers.dart';
/// ```
///
/// ## Why this only lists one export per Core subsystem
///
/// This barrel used to list every individual provider file directly — and
/// once silently drifted out of sync with what Core actually provides: it
/// omitted `failureMapperProvider`, `talkerProvider`,
/// `accessTokenReaderProvider`, and `sharedPreferencesProvider` despite
/// promising "all infrastructure providers," forcing `posts_providers.dart`
/// to import `failure_mapper.dart` directly to work around the gap. The
/// bug was invisible to the compiler — nothing forces every new Core
/// provider file to be referenced here, so a forgotten export line just
/// silently produces a barrel that's slightly less complete than it
/// claims to be, discovered only when some future caller goes looking
/// for a provider that isn't there.
///
/// That drift surface is now much smaller: each Core subsystem owns its
/// own `<subsystem>.dart` barrel, co-located in that subsystem's own
/// folder (`core/network/network.dart`, `core/theme/theme.dart`, etc.).
/// Adding a new provider *within* an existing subsystem means editing a
/// file in the same folder already being worked in — far more
/// discoverable than remembering a distant top-level file exists. This
/// file only needs to change when an entirely new Core subsystem is
/// introduced, which is rare, and whoever adds a new top-level `core/`
/// folder is already touching `core/` broadly enough to notice this file
/// sitting right next to it.
///
/// Same shape of fix as `core/routing/feature_registry.dart` — that file
/// closes the equivalent drift gap between route registration and nav
/// destinations (two parallel lists that had to stay manually synced);
/// this barrel only ever had one list, so the fix here is "make the one
/// list short and stable" rather than "merge two lists into one."
library;

export '../env/env.dart';
export '../errors/errors.dart';
export '../logging/logging.dart';
export '../network/network.dart';
export '../observability/observability.dart';
export '../routing/routing.dart';
export '../storage/storage.dart';
export '../theme/theme.dart';
// package_infoProvider is generated by riverpod_generator.
export 'package_info_provider.dart';
// sharedPreferencesProvider is generated by riverpod_generator.
export 'shared_preferences_provider.dart';
