/// Central dependency injection barrel.
///
/// Import this single file anywhere in the app to access all infrastructure
/// providers. Feature-level providers (notifiers, use cases) are co-located
/// with their features and do NOT need to be re-exported here.
///
/// Usage:
/// ```dart
/// import 'package:token_shell_riverpod/core/di/providers.dart';
/// ```
library;

// ── Errors ────────────────────────────────────────────────────────────────────
// Pure Dart — no codegen involved; show clause is safe here.
export '../errors/failure.dart'
    show CacheFailure, Failure, NetworkFailure, ServerFailure, UnknownFailure;
export '../network/connectivity_provider.dart';
// ── Network ───────────────────────────────────────────────────────────────────
// Same rationale: dioProvider is generated by riverpod_generator.
export '../network/dio_client.dart';
// ── Routing ───────────────────────────────────────────────────────────────────
// appRouterProvider is generated by riverpod_generator.
export '../routing/app_router.dart';
// ── Theme ─────────────────────────────────────────────────────────────────────
// Exported without a `show` clause: generated provider names
// (themeModeProvider, sharedPreferencesProvider, lightThemeProvider,
// darkThemeProvider) are produced by build_runner and not visible to the
// analyzer until codegen runs — a `show` clause would cause analysis errors
// before the first build.
export 'theme_provider.dart';
