/// Barrel for the Environment subsystem.
///
/// Exported as a whole from `core/di/providers.dart` — add new
/// Environment provider/type files here, in the same folder you're
/// already editing, rather than remembering to also touch the distant
/// top-level barrel. See `core/di/providers.dart`'s doc comment for the
/// drift problem this folder-local barrel exists to avoid.
library;

// appFlavorProvider is generated by riverpod_generator.
// AppFlavor enum is re-exported so callers do not need a separate import
// when branching on the current flavor (e.g. if (flavor == AppFlavor.prod)).
export 'app_flavor.dart';
